version: '3.7'
services:
  db:
      image: mysql:5.7
      #command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: crudnodejsmysql
        MYSQL_USER: user
        MYSQL_PASSWORD: user
      volumes: 
        #- ./.mysqldata:/var/lib/mysql:rw
        - ./database:/docker-entrypoint-initdb.d:ro
      ports:
        - 3306:3306
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: crudnodejsmysql
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    depends_on:
        - "db"
    working_dir: /usr/src/app
  